require('settings')

require('keybindings')
require('keybindings.competitest')
require('keybindings.lazygit')
require('keybindings.nvim-tree')
require('keybindings.telescope')
require('keybindings.vimspector')
require('keybindings.undotree')

require('plugins')
require('plugins.auto-pairs')
require('plugins.lsp-zero')
require('plugins.lsp_signature')
require('plugins.lualine')
require('plugins.LuaSnip')
require('plugins.colorscheme')
require('plugins.nvim-tree')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.vimspector')
require('plugins.nvim-cmp')
require('plugins.bufferline')
require('plugins.indent-blankline')

