require('settings')

require('keybindings')
require('keybindings.nvim-tree')
require('keybindings.lazygit')
require('keybindings.telescope')
require('keybindings.vimspector')
require('keybindings.nvim-lspconfig')
require('keybindings.competitest')

require('plugins')
require('plugins.material')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.nvim-tree')
require('plugins.auto-pairs')
require('plugins.nvim-lsp-installer')
require('plugins.nvim-cmp')
require('plugins.LuaSnip')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.vimspector')

