map("n", "<leader>dd", ":call vimspector#Launch()<CR>")
map("n", "<leader>de", ":call vimspector#Reset()<CR>")
map("n", "<leader>db", "<Plug>VimspectorToggleBreakpoint")
map("n", "<leader>dB", "<Plug>VimspectorToggleConditionalBreakpoint")
map("n", "<leader>dj", "<Plug>VimspectorStepOver")
map("n", "<leader>dl", "<Plug>VimspectorStepInto")
map("n", "<leader>dk", "<Plug>VimspectorStepOut")
map("n", "<leader>dc", "<Plug>VimspectorContinue")
map("n", "<leader>dh", "<Plug>VimspectorRunToCursor")
